In [1]:
import tensorflow as tf
from tensorflow.keras import layers, Model
from tensorflow import keras




In [23]:
class Dense_Process_Layer(layers.Layer):
    def __init__(self, sparse_features, dense_features, price_features):
        self.sparse_features = sparse_features
        self.dense_features = dense_features
        self.price_features = price_features
        self.concat_layer = layers.Concatenate()
    
    def call(self, inputs):
        concat_numeric = []
        for name, input in inputs.items():
            if name in dense_features:
                if name not in price_features:
                    temp_feature = tf.math.log1p(input) /  tf.math.log(tf.constant(2.0, dtype=tf.float32))
                else:
                    temp_feature = tf.math.log1p(input) /   tf.math.log(tf.constant(10.0, dtype=tf.float32))
                concat_numeric.append(temp_feature)

        return self.concat_layer(concat_numeric, axis = 1)
        
class 

In [ ]:
class EveryDayModel(Model):
    def __init__(self, inputs,  sparse_features, dense_features, price_features):
        self.embedding_dict = {}
        num_bins = 1000
        for name in sparse_features:
            self.embedding_dict[name] = layers.Embedding(num_bins, 8)
        self.dense_process_layer = Dense_Process_Layer(sparse_features, dense_features, price_features)
        
        

In [16]:
embedding = layers.Embedding(4, 8)
embedding(tf.constant([1,2]))

<tf.Tensor: shape=(2, 8), dtype=float32, numpy=
array([[-0.00070654,  0.00420493, -0.03968285, -0.04753124,  0.00853604,
         0.00776973, -0.00496557, -0.01848469],
       [ 0.04521557,  0.01046337,  0.04815224,  0.00645217,  0.03880386,
        -0.04316054,  0.02612242,  0.00133228]], dtype=float32)>

In [17]:
embedding.get_weights()

[array([[-0.01498637, -0.03534583, -0.04598365,  0.01964403, -0.03970485,
         -0.00461344,  0.0303312 ,  0.02263702],
        [-0.00070654,  0.00420493, -0.03968285, -0.04753124,  0.00853604,
          0.00776973, -0.00496557, -0.01848469],
        [ 0.04521557,  0.01046337,  0.04815224,  0.00645217,  0.03880386,
         -0.04316054,  0.02612242,  0.00133228],
        [-0.02562811,  0.02902894,  0.00148463, -0.03228058, -0.02536453,
         -0.00539424, -0.01763015, -0.00038519]], dtype=float32)]

In [22]:
embedding(tf.constant([1,2]))

<tf.Tensor: shape=(2, 8), dtype=float32, numpy=
array([[-0.00070654,  0.00420493, -0.03968285, -0.04753124,  0.00853604,
         0.00776973, -0.00496557, -0.01848469],
       [ 0.04521557,  0.01046337,  0.04815224,  0.00645217,  0.03880386,
        -0.04316054,  0.02612242,  0.00133228]], dtype=float32)>